StartingMessage: "[HOTSLICERRPG] Plugin Enabled"
NoPerms: "&cYou are not permitted to run this command!"
ConsoleWarning: "&cYou cannot run this command as console!"

Portals:
  One:
    Item: Skull
    Head:
      ID: "d54c8e17-7da2-4255-b3af-4ca87f404a51"
      Value: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDM0NjdhNTMxOTc4ZDBiOGZkMjRmNTYyODVjNzI3MzRkODRmNWVjODhlMGI0N2M0OTMyMzM2Mjk3OWIzMjNhZiJ9fX0="
    DisplayName: "Spawn"
    Description:
      - "Go to spawn owo!!"
      - "uwu"
      - "ewe"
    Slot: 1
    X: -68.5
    Y: 115
    Z: 610.5
  Two:
    Item: Grass
    Slot: 2
    X: -41.5
    Y: 78
    Z: 618.5
  Three:
    Item: Wood
    Slot: 3
    X: -60.5
    Y: 99
    Z: 637.5

#DO NOT TOUCH!!!
